# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4acdf397dc0221e62bc502d24dd34a22"
name = "live metal price"
application_url = "https://live-metal-price.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://live-metal-price.onrender.com/api/auth/callback" ]
